"""Run an arbitrary bash payload on a short-lived GCE VM, with GCS for I/O.

Use this whenever the sandbox blocks the work you need to do — CAPTCHA on a
fetch, egress policy denial, OOM under sandbox memory, or anything that
needs a GPU. The wrapper takes care of the boring parts: provisioning the
VM, wrapping your payload in a startup script that uploads logs/output to
GCS, polling for completion, fetching the result, and (because of
`--instance-termination-action=DELETE` + `--max-run-duration`) ensuring the
VM auto-cleans even if something goes wrong.

The contract with your payload script:

    * It is invoked as a Bash startup script on a fresh Debian 12 VM that
      already has `curl`, `python3`, and the Cloud SDK (`gcloud`/`gsutil`)
      preinstalled and authenticated as the project's service account.
    * Two environment variables are exported for it:
        - $RUN_ID    — the run identifier (also encoded in the GCS prefix)
        - $RUN_GCS   — gs://<bucket>/scratch/cloud_runner/<RUN_ID>/
      Anything you put under $RUN_GCS will be picked up after the VM dies.
    * It MUST end by writing a `DONE.txt` marker to $RUN_GCS so the wrapper
      knows to stop polling. The wrapper provides a `mark_done` shell
      helper (sourced before your payload runs) — call `mark_done` at the
      end. The helper also captures the full startup log to
      $RUN_GCS/startup.log automatically.
    * Anything written to /tmp/output (a directory) gets rsynced to
      $RUN_GCS/output/ on completion, so a typical pattern is:

          curl -sL "$URL" -o /tmp/output/page.html

Examples:

    # 1. Inline payload — bash one-liner equivalent.
    uv run python scripts/cloud_runner.py \\
        --bucket cot-rosetta-interp-data \\
        --inline 'curl -sL https://www.uklo.org/past-exam-papers/ -o /tmp/output/page.html'

    # 2. Payload from a file.
    uv run python scripts/cloud_runner.py \\
        --bucket cot-rosetta-interp-data \\
        --script /path/to/payload.sh

    # 3. Bigger machine for a memory-heavy job.
    uv run python scripts/cloud_runner.py \\
        --bucket cot-rosetta-interp-data \\
        --machine-type e2-standard-4 \\
        --script payload.sh

When the run finishes the wrapper prints the GCS URI of the output and (if
`--fetch-output` is set) downloads `output/` to a local directory.

This wrapper does NOT support GPUs or VPC-attached VMs — those need
hand-tuned configuration. For one-off CPU work where you just need
unrestricted egress and a place to land bytes, this is the right tool.
"""

from __future__ import annotations

import argparse
import datetime as dt
import secrets
import subprocess
import sys
import time
from pathlib import Path

WRAPPER_PRELUDE = r"""#!/bin/bash
# Auto-generated by scripts/cloud_runner.py. Do not edit on the VM.
set -x
exec > /tmp/startup.log 2>&1

export RUN_ID="__RUN_ID__"
export RUN_GCS="gs://__BUCKET__/scratch/cloud_runner/__RUN_ID__/"

mkdir -p /tmp/output

mark_done() {
  local rc="${1:-0}"
  gsutil -q cp /tmp/startup.log "${RUN_GCS}startup.log" || true
  if [ -d /tmp/output ] && [ -n "$(ls -A /tmp/output 2>/dev/null)" ]; then
    gsutil -q -m rsync -r /tmp/output "${RUN_GCS}output/" || true
  fi
  printf 'rc=%s end=%s\n' "$rc" "$(date -u +%FT%TZ)" > /tmp/done.txt
  gsutil -q cp /tmp/done.txt "${RUN_GCS}DONE.txt" || true
  shutdown -h +1
}
trap 'mark_done $?' EXIT

# --- user payload starts here ---
"""


def _check_gcloud() -> None:
    try:
        subprocess.run(["gcloud", "--version"], check=True, capture_output=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        sys.exit(f"gcloud is required on PATH: {exc}")


def _run(*args: str, capture: bool = False, check: bool = True) -> str:
    cmd = ["gcloud", *args]
    print("$ " + " ".join(cmd), flush=True)
    res = subprocess.run(cmd, check=check, capture_output=capture, text=True)
    return res.stdout if capture else ""


def _gcs_exists(uri: str) -> bool:
    res = subprocess.run(
        ["gcloud", "storage", "ls", uri], capture_output=True, text=True
    )
    return res.returncode == 0


def _gcs_cat(uri: str) -> str:
    return subprocess.check_output(["gcloud", "storage", "cat", uri], text=True)


def render_startup(bucket: str, run_id: str, payload: str) -> str:
    prelude = WRAPPER_PRELUDE.replace("__BUCKET__", bucket).replace(
        "__RUN_ID__", run_id
    )
    payload_stripped = payload.lstrip()
    if payload_stripped.startswith("#!"):
        # Drop the user's shebang — we're already inside a bash heredoc.
        payload = payload_stripped.split("\n", 1)[1] if "\n" in payload_stripped else ""
    return prelude + "\n" + payload + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bucket", required=True, help="GCS bucket to use for I/O.")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--script", type=Path, help="Path to a Bash payload script.")
    src.add_argument("--inline", help="Inline Bash one-liner.")
    ap.add_argument("--zone", default="us-central1-a")
    ap.add_argument("--machine-type", default="e2-small")
    ap.add_argument(
        "--service-account",
        default="claude-agent@cot-rosetta-interp.iam.gserviceaccount.com",
    )
    ap.add_argument("--max-wait-min", type=int, default=15)
    ap.add_argument(
        "--instance-name",
        default=None,
        help="VM name. Auto-generated if omitted.",
    )
    ap.add_argument(
        "--fetch-output",
        type=Path,
        default=None,
        help="If set, rsync $RUN_GCS/output/ to this local dir on success.",
    )
    ap.add_argument(
        "--keep-vm",
        action="store_true",
        help="Skip the auto-delete safety nets (use only for debugging).",
    )
    args = ap.parse_args(argv)

    _check_gcloud()

    payload = args.script.read_text() if args.script else args.inline
    if not payload or not payload.strip():
        sys.exit("Payload is empty.")

    run_id = (
        dt.datetime.utcnow().strftime("%Y%m%d-%H%M%S") + "-" + secrets.token_hex(3)
    )
    instance = args.instance_name or f"cloud-runner-{run_id}"
    startup = render_startup(args.bucket, run_id, payload)
    startup_path = Path("/tmp") / f"{instance}.startup.sh"
    startup_path.write_text(startup)
    print(f"Run ID: {run_id}")
    print(f"Output prefix: gs://{args.bucket}/scratch/cloud_runner/{run_id}/")
    print(f"Startup script: {startup_path}")

    create_args = [
        "compute", "instances", "create", instance,
        f"--zone={args.zone}",
        f"--machine-type={args.machine_type}",
        "--image-family=debian-12",
        "--image-project=debian-cloud",
        f"--service-account={args.service_account}",
        "--scopes=https://www.googleapis.com/auth/cloud-platform",
        f"--metadata-from-file=startup-script={startup_path}",
        "--no-shielded-secure-boot",
    ]
    if not args.keep_vm:
        create_args += [
            "--instance-termination-action=DELETE",
            f"--max-run-duration={args.max_wait_min}m",
        ]
    _run(*create_args)

    done_uri = f"gs://{args.bucket}/scratch/cloud_runner/{run_id}/DONE.txt"
    deadline = time.time() + args.max_wait_min * 60
    print(f"Polling {done_uri} (timeout {args.max_wait_min}m)…", flush=True)
    while time.time() < deadline:
        if _gcs_exists(done_uri):
            print("DONE:", _gcs_cat(done_uri).strip())
            break
        time.sleep(15)
    else:
        print("Timed out before DONE marker appeared.", file=sys.stderr)
        if not args.keep_vm:
            _run(
                "compute", "instances", "delete", instance,
                f"--zone={args.zone}", "--quiet", check=False,
            )
        return 2

    log_uri = f"gs://{args.bucket}/scratch/cloud_runner/{run_id}/startup.log"
    if _gcs_exists(log_uri):
        print(f"Last 20 lines of {log_uri}:")
        for line in _gcs_cat(log_uri).splitlines()[-20:]:
            print(f"  {line}")

    if args.fetch_output:
        args.fetch_output.mkdir(parents=True, exist_ok=True)
        _run(
            "storage", "rsync", "--recursive",
            f"gs://{args.bucket}/scratch/cloud_runner/{run_id}/output/",
            str(args.fetch_output),
            check=False,
        )
        print(f"Output rsynced to {args.fetch_output}")

    # Belt and braces: even with --instance-termination-action=DELETE we
    # explicitly issue a delete in case shutdown -h didn't fire.
    if not args.keep_vm:
        _run(
            "compute", "instances", "delete", instance,
            f"--zone={args.zone}", "--quiet", check=False,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
